# Generated by Django 4.1.4 on 2023-04-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='file',
            field=models.FileField(default=1, upload_to='documents/'),
            preserve_default=False,
        ),
    ]
