# Generated by Django 4.1.4 on 2023-04-20 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='file',
        ),
    ]
