# Generated by Django 4.1.4 on 2023-04-20 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_remove_task_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='user',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='List',
        ),
    ]
