# Generated by Django 4.1.4 on 2023-05-23 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_remove_list_user_delete_assignment_delete_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='task',
            name='completed_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='updated_at',
        ),
    ]
